/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package empty.gradle.multi.project;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App2 classUnderTest = new App2();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
