/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package empty.gradle.multi.project;

public class App2 {
    public String getGreeting() {
        return "I am app 2!";
    }

    public static void main(String[] args) {
        System.out.println(new App2().getGreeting());
    }
}
